[versions]
kotlin = "2.2.20"
web3 = "0.3.0"
rpc = "0.2.10"

[libraries]
web3-solana = { group = "com.solanamobile", name = "web3-solana", version.ref = "web3" }
rpc-solana = { group = "com.solanamobile", name = "rpc-solana", version.ref = "rpc" }


[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
